version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nextcloud-staging/
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 200
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
